import { useEffect, useState } from 'react';

/**
 * The court-card art and suit pips live in one SVG sprite (public/cards.svg, generated by
 * tools/build-sprite.py from the English-pattern deck). It is fetched once and injected into the
 * document so cards can reference its symbols with <use href="#face-QH">; browsers do not resolve
 * <use> against a separate file, so injecting is the only portable option.
 *
 * It is deliberately not bundled into the JS: at ~200KB gzipped it would hold up first paint, and
 * as a separate file the service worker caches it after the first visit.
 */
const SPRITE_URL = '/cards.svg';

let state: 'idle' | 'loading' | 'ready' | 'failed' = 'idle';
const waiting = new Set<() => void>();

function settle(next: 'ready' | 'failed') {
  state = next;
  for (const notify of waiting) notify();
  waiting.clear();
}

function load() {
  if (state !== 'idle') return;
  state = 'loading';

  fetch(SPRITE_URL)
    .then((res) => (res.ok ? res.text() : Promise.reject(new Error(String(res.status)))))
    .then((markup) => {
      const host = document.createElement('div');
      // Not display:none - some browsers refuse to resolve <use> into a fully hidden subtree.
      host.setAttribute('aria-hidden', 'true');
      host.style.cssText = 'position:absolute;width:0;height:0;overflow:hidden';
      host.innerHTML = markup;
      document.body.prepend(host);
      settle('ready');
    })
    .catch(() => settle('failed'));
}

/** True once the sprite's symbols can be referenced. Cards fall back to plain faces until then. */
export function useCardSprite(): boolean {
  const [ready, setReady] = useState(state === 'ready');

  useEffect(() => {
    if (state === 'ready') {
      setReady(true);
      return;
    }
    const notify = () => setReady(state === 'ready');
    waiting.add(notify);
    load();
    return () => {
      waiting.delete(notify);
    };
  }, []);

  return ready;
}
